### ISSUE TITLE
M.U.G.E.N and Stepmania, EasyRPG? - Add it as cores?

### ISSUE THREAD

**Issue by Gron21** [forkymcforkface/RGBPi-Extra#14]
Will you add: MUGEN and Stepmania?

And i don´t know if system support it... EasyRPG?

**Comment by forkymcforkface** [comment]
@Gron21 Do you have a link to current cores?

**Comment by Gron21** [comment]
- EasyRPG: 

https://easyrpg.org/downloads/player/ - Don´t know what exactly file is

Here is another: https://buildbot.libretro.com/nightly/linux/ But don´t know exactly what arm is but inside is easyrpg core...

Method to build lr core: https://github.com/EasyRPG/Player/blob/master/docs/BUILDING.md

- MUGEN: It´s Ikemen GO

https://github.com/LucasFebatis/Ikemen-GO-Plus - RPi3
https://github.com/danielporto/Ikemen_GO/releases/tag/19.04.2019 - Another RPi3 ??

https://github.com/ikemen-engine/Ikemen-GO/wiki/Building,-Installing-and-Distributing   - Instructions to build in RPi??

- Stepmania: 

Here is a way to make it arcade in RPi: https://github.com/SpottyMatt/raspbian-stepmania-arcade

Project OutFox: Fork from Stepmania 5 to RPi

https://projectoutfox.com/releases/0.4.19#dl-links

If in official page don´t mention, here is a guide:

https://www.reddit.com/r/Stepmania/comments/psd1hm/raspberry_pi_4_stepmania_outfox_53_guide/

Hope this help, because i don´t know anything about linux....

**Comment by forkymcforkface** [comment]
I got easyrpg 2000/2003 core working, just need to add it as a package. there are some dependencies that make it a bit different than the other cores.

**Comment by forkymcforkface** [comment]
easyrpg only looks to work on pi5 version.
