### ISSUE TITLE
WINDOW_SIZE height cutoff

### ISSUE THREAD

**Issue by danielkoellmann** [forkymcforkface/RGBPi-Extra#3]
Hi Kev,

I saw you made adjustments by reducing the width of the WINDOW_SIZE which looks great. Thanks for that. I noticed though that the height still has a cutoff at the bottom of the screen which makes the last row unreadable. Maybe if you reduce the height as well it could solve the problem. I've attached a picture for you to see how it looks on my CRT. Thanks in advance and great work as usual. Respect!

![IMG_20240522_174720951](https://github.com/forkymcforkface/RGBPi-Extra/assets/34703673/3b49a913-ef99-4d40-9315-4cde8038fe81)

**Comment by forkymcforkface** [comment]
I'll take a look when I have time. You have a lot of overscan?

**Comment by danielkoellmann** [comment]
No worries. "A lot" is relative. When I compare it to all the RGB-Pi skins for example the difference is massive. Nothing is cut that drastically. I don't know what resolution you are working with in RGB-Pi Extra but maybe decreasing that could help, instead of working with margins. I'm not a professional, but I can tell that there is way much more overscan in your Menu compared to anything else. Remember I was not the only one with these issues. Other people on Discord had exactly the same problem, so nothing wrong with my TV set or geometry settings.

**Comment by forkymcforkface** [comment]
On my screen there is a small amount of cutoff initially, but when you scroll around the menu the back button is fully visible.

**Comment by danielkoellmann** [comment]
![IMG_20240531_175002246](https://github.com/forkymcforkface/RGBPi-Extra/assets/34703673/b91049a5-c2b8-43e0-8b0d-b231c2a76681)
Yeah mine looks similar. I know how to work with it. It's fine. I'll live with it.

**Comment by forkymcforkface** [comment]
Thanks for understanding. At the end of the day I'm not a developer and have been relying 99% on AI to help. Im an architect by trade and can read code, but never learned to write it myself.

**Comment by danielkoellmann** [comment]
It's all good. Should I close the issue or should we just leave it as it is?
